services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/taskmanager
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/backend/app
    volumes:
      - ./backend:/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/taskmanager
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/backend/app
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: celery -A app.workers.celery_app worker --loglevel=info

  # Celery Beat Scheduler
  celery-beat:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/taskmanager
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/backend/app
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: celery -A app.workers.celery_app beat --loglevel=info

volumes:
  postgres_data:
